const authController = require('./controllers/authController')
const authTemplate = require('./controllers/authTemplate')
const authJournal = require('./controllers/authJournal')
const authHabit = require('./controllers/authHabit')
const authMood = require('./controllers/authMood')
const authJournalView = require('./controllers/authJournalView')

const router = require('express').Router()

router.post('/login', authController.user_login)
router.post('/signup', authController.user_signup)
router.post('/load_user', authController.load_user)
router.post('/update_recent', authController.update_recent)
router.post('/find_recent', authJournalView.find_recent)
router.post('/loadTemplate', authTemplate.load_template)
router.post('/createTemplate', authTemplate.create_template)
router.post('/initialization', authTemplate.initialize)
router.post('/updateCanvas', authTemplate.update_canvas)
router.post('/requestBuffer', authTemplate.request_buffer)
router.post('/createHabit', authHabit.create_habit)
router.post('/updateHabit', authHabit.update_habit)
router.post('/loadHabit', authHabit.load_habit)
router.post('/deleteHabit', authHabit.delete_habit)
router.post('/loadHabitLists', authHabit.load_habit_lists)
router.post('/produceJournal', authJournal.produce_journal)
router.post('/createJournal', authJournal.create_journal)
router.post('/loadJournal', authJournal.load_journal)
router.post('/deleteJournal', authJournal.delete_journal)
router.post('/duplicateTemplate', authTemplate.duplicate_template)
router.post('/deleteTemplate', authTemplate.delete_template)
router.post('/check_thumbnail_template', authTemplate.check_thumbnail)
router.post('/update_thumbnail_template', authTemplate.update_thumbnail)
router.post('/check_thumbnail_journal', authJournalView.check_thumbnail)
router.post('/update_thumbnail_journal', authJournalView.update_thumbnail)
router.post('/loadMoodLists', authMood.load_mood_lists)
router.post('/createMood', authMood.create_mood)
router.post('/deleteMood', authMood.delete_mood)
router.post('/updateMood', authMood.update_mood)
router.post('/loadMood', authMood.load_mood)
router.post('/initialize_journal', authJournalView.load_journal)

module.exports = router